In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Way - 1

In [2]:
x = torch.tensor([-1.0, 0.0, 2.0])
relu_out = F.relu(x)
print(relu_out)  # tensor([0., 0., 2.])

tensor([0., 0., 2.])


### Way - 2

In [3]:
x = torch.tensor([-1.0, 0.0, 2.0])
relu = nn.ReLU()
relu_out = relu(x)
print(relu_out)

tensor([0., 0., 2.])


### Way - 3

In [4]:
x = torch.tensor([-1.0, 0.0, 2.0])
relu_out = torch.clamp(x, min=0)
print(relu_out)

tensor([0., 0., 2.])


### Way - 4

In [5]:
x = torch.tensor([-1.0, 0.0, 2.0])
x [x < 0] = 0
print(x)

tensor([0., 0., 2.])


### Way - 5

In [6]:
x = torch.tensor([-1.0, 0.0, 2.0])
zero_tensor = torch.zeros_like(x)
relu_out = torch.maximum(x, zero_tensor)
print(relu_out)

tensor([0., 0., 2.])


### Way - 6

In [7]:
x = torch.tensor([-1.0, 0.0, 2.0])
mask = x < 0                    # Identify negative values
relu_out = x.masked_fill(mask, 0.0)
print(relu_out)  # tensor([0., 0., 2.])

tensor([0., 0., 2.])
