In [1]:
# self attention

In [2]:
import torch

In [3]:
# sentence = "self attention demo"
x = torch.randn(3,4)

In [4]:
x

tensor([[ 0.7373,  0.3671, -1.4128,  0.6807],
        [-1.2768, -0.2062,  0.5206, -3.0519],
        [ 1.4501,  1.6386,  0.4531,  0.2745]])

In [5]:
w_q = torch.randn(4,2)

In [6]:
w_k = torch.randn(4,2)

In [7]:
w_v = torch.randn(4,2)

In [8]:
Q = x @ w_q
K = x @ w_k
V = x @ w_v

In [9]:
scores = Q @ K.T

In [10]:
scores

tensor([[ -2.6887,   9.1645,  -6.1777],
        [  5.2639, -18.2668,  30.3794],
        [ -4.0348,  13.6788,  -5.1203]])

In [11]:
d_k = Q.shape[-1]

In [12]:
d_k

2

In [13]:
scores = scores/torch.sqrt(torch.tensor(d_k, dtype=torch.float32))

In [14]:
scores

tensor([[ -1.9012,   6.4803,  -4.3683],
        [  3.7221, -12.9166,  21.4814],
        [ -2.8530,   9.6724,  -3.6206]])

In [15]:
exp_scores = torch.exp(scores)
row_sum = exp_scores.sum(dim=-1, keepdim=True)
atten_weights = exp_scores/row_sum

In [16]:
atten_weights

tensor([[2.2900e-04, 9.9975e-01, 1.9426e-05],
        [1.9374e-08, 1.1511e-15, 1.0000e+00],
        [3.6330e-06, 9.9999e-01, 1.6863e-06]])

In [17]:
exp_scores

tensor([[1.4939e-01, 6.5216e+02, 1.2672e-02],
        [4.1353e+01, 2.4570e-06, 2.1344e+09],
        [5.7669e-02, 1.5873e+04, 2.6767e-02]])

In [18]:
row_sum

tensor([[6.5233e+02],
        [2.1344e+09],
        [1.5873e+04]])

In [19]:
out = atten_weights @ V

In [20]:
out

tensor([[-5.9810,  0.1907],
        [ 0.3527,  1.5284],
        [-5.9826,  0.1910]])

In [21]:
w_next = torch.randn(2,4)

In [22]:
embeddings_next = out @ w_next

In [23]:
embeddings_next

tensor([[-4.5297,  5.6394,  3.7796,  5.6330],
        [ 1.8909,  0.7105,  0.4690, -1.8247],
        [-4.5307,  5.6410,  3.7807,  5.6343]])