In [1]:
# leaky relu activation

### **LeakyReLU Activation Function**

**LeakyReLU (Leaky Rectified Linear Unit)** is an activation function used in neural networks, particularly in deep learning models. It aims to address the "dying ReLU" problem by allowing a small, non-zero gradient when the unit is not active (i.e., when the input is negative).

### Formula

$$
f(x) =
\begin{cases}
x, & \text{if } x \geq 0 \\
\alpha x, & \text{if } x < 0
\end{cases}
$$

- \( x \): Input to the activation function
- \( alpha \): Small positive constant (commonly 0.01)

### Properties

- **Non-linearity**: Allows the network to learn complex patterns.
- **Avoids dying ReLUs**: Small slope for negative inputs prevents neurons from becoming inactive.
- **Computationally efficient**: Simple and fast to compute.


In [2]:
import torch
import torch.nn as nn

# Create a (3, 2) tensor with random normal values
x = torch.randn(3, 2)

# Define slope for negative values
alpha = 0.01

# Apply LeakyReLU using PyTorch built-in function
y_builtin = nn.LeakyReLU(negative_slope=0.01)
y_builtin = y_builtin(x)

# Apply LeakyReLU manually
y_manual = torch.where(x >= 0, x, alpha * x)

# Print results
print("Input:\n", x)
print("-------------------------------------------")
print("LeakyReLU (torch built-in):\n", y_builtin)
print("-------------------------------------------")
print("LeakyReLU (manual computation):\n", y_manual)

Input:
 tensor([[-0.0451,  0.2639],
        [ 0.2314, -0.9714],
        [-0.3198, -1.0708]])
-------------------------------------------
LeakyReLU (torch built-in):
 tensor([[-0.0005,  0.2639],
        [ 0.2314, -0.0097],
        [-0.0032, -0.0107]])
-------------------------------------------
LeakyReLU (manual computation):
 tensor([[-0.0005,  0.2639],
        [ 0.2314, -0.0097],
        [-0.0032, -0.0107]])
