In [1]:
# ReLU activation

### ReLU (Rectified Linear Unit)

The ReLU function is defined as:

$$
\text{ReLU}(x) = \max(0, x)
$$

This means:
$$
\text{If } x > 0, \text{ then } \text{ReLU}(x) = x \\
\text{If } x <= 0, \text{ then } \text{ReLU}(x) = 0
$$




In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### Way - 1

In [3]:
x = torch.tensor([-1.0, 0.0, 2.0])
relu_out = F.relu(x)
print(relu_out)  # tensor([0., 0., 2.])

tensor([0., 0., 2.])


### Way - 2

In [4]:
x = torch.tensor([-1.0, 0.0, 2.0])
relu = nn.ReLU()
relu_out = relu(x)
print(relu_out)

tensor([0., 0., 2.])


### Way - 3

In [5]:
x = torch.tensor([-1.0, 0.0, 2.0])
relu_out = torch.clamp(x, min=0)
print(relu_out)

tensor([0., 0., 2.])


### Way - 4

In [6]:
x = torch.tensor([-1.0, 0.0, 2.0])
x [x < 0] = 0
print(x)

tensor([0., 0., 2.])


### Way - 5

In [7]:
x = torch.tensor([-1.0, 0.0, 2.0])
zero_tensor = torch.zeros_like(x)
relu_out = torch.maximum(x, zero_tensor)
print(relu_out)

tensor([0., 0., 2.])


### Way - 6

In [8]:
x = torch.tensor([-1.0, 0.0, 2.0])
mask = x < 0                    # Identify negative values
relu_out = x.masked_fill(mask, 0.0)
print(relu_out)  # tensor([0., 0., 2.])

tensor([0., 0., 2.])
