In [ ]:
# Sigmoid activation

The **sigmoid function** maps any real-valued number to a value between **0 and 1** using the formula:  

$$
\sigma(x) = \frac{1}{1 + e^{-x}}
$$

It is commonly used in machine learning to convert outputs into probabilities.

In [5]:
import torch

# Create a (3, 2) tensor with random normal values
x = torch.randn(3, 2)

# Apply sigmoid (built-in)
y = torch.sigmoid(x)

# OR manually (optional)
y_manually = 1 / (1 + torch.exp(-x))

print("Input:\n", x)
print("-------------------------------------------")
print("Sigmoid Output:\n", y)
print("-------------------------------------------")
print("Sigmoid Output Manually:\n", y_manually)

Input:
 tensor([[-0.2463,  0.2668],
        [-1.1206,  1.2460],
        [ 0.6280,  0.7460]])
-------------------------------------------
Sigmoid Output:
 tensor([[0.4387, 0.5663],
        [0.2459, 0.7766],
        [0.6520, 0.6783]])
-------------------------------------------
Sigmoid Output Manually:
 tensor([[0.4387, 0.5663],
        [0.2459, 0.7766],
        [0.6520, 0.6783]])
