In [ ]:
# tanh activation

The **tanh (hyperbolic tangent) activation function** maps any real-valued number to a value between **-1 and 1** using the formula:

$$
\tanh(x) = \frac{e^x - e^{-x}}{e^x + e^{-x}}
$$

It is commonly used in neural networks because it is **zero-centered** and can help with faster convergence during training.

In [7]:
import torch

# Create a (3, 2) tensor with random normal values
x = torch.randn(3, 2)

# Apply tanh using PyTorch's built-in function
y = torch.tanh(x)

# Apply tanh manually using the definition
y_manually = (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

# Print results
print("Input:\n", x)
print("-------------------------------------------")
print("tanh (torch built-in):\n", y)
print("-------------------------------------------")
print("tanh (manual computation):\n", y_manually)

Input:
 tensor([[ 0.2582,  0.7962],
        [ 0.3152, -0.0294],
        [ 1.9997,  0.3793]])
-------------------------------------------
tanh (torch built-in):
 tensor([[ 0.2526,  0.6619],
        [ 0.3052, -0.0294],
        [ 0.9640,  0.3621]])
-------------------------------------------
tanh (manual computation):
 tensor([[ 0.2526,  0.6619],
        [ 0.3052, -0.0294],
        [ 0.9640,  0.3621]])
